# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{redhillonrails_core}
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Micha\305\202 \305\201omnicki"]
  s.date = %q{2011-01-09}
  s.description = %q{Adds support in ActiveRecord for foreign_keys, complex indexes and other database-related stuff. Easily create foreign_keys, complex indexes and views.}
  s.email = %q{michal.lomnicki@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "CHANGELOG",
     "MIT-LICENSE",
     "README.rdoc",
     "init.rb",
     "lib/redhillonrails_core.rb",
     "lib/redhillonrails_core/active_record/base.rb",
     "lib/redhillonrails_core/active_record/connection_adapters/abstract_adapter.rb",
     "lib/redhillonrails_core/active_record/connection_adapters/column.rb",
     "lib/redhillonrails_core/active_record/connection_adapters/foreign_key_definition.rb",
     "lib/redhillonrails_core/active_record/connection_adapters/index_definition.rb",
     "lib/redhillonrails_core/active_record/connection_adapters/mysql_adapter.rb",
     "lib/redhillonrails_core/active_record/connection_adapters/mysql_column.rb",
     "lib/redhillonrails_core/active_record/connection_adapters/postgresql_adapter.rb",
     "lib/redhillonrails_core/active_record/connection_adapters/sqlite3_adapter.rb",
     "lib/redhillonrails_core/active_record/connection_adapters/table_definition.rb",
     "lib/redhillonrails_core/active_record/schema.rb",
     "lib/redhillonrails_core/active_record/schema_dumper.rb",
     "redhillonrails_core.gemspec"
  ]
  s.homepage = %q{http://github.com/mlomnicki/redhillonrails_core}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Adds support in ActiveRecord for foreign_keys, complex indexes and other database-related stuff}
  s.test_files = [
    "spec/schema/schema.rb",
     "spec/foreign_key_spec.rb",
     "spec/schema_dumper_spec.rb",
     "spec/connections/mysql2/connection.rb",
     "spec/connections/postgresql/connection.rb",
     "spec/connections/sqlite3/connection.rb",
     "spec/connections/mysql/connection.rb",
     "spec/support/reference.rb",
     "spec/index_definition_spec.rb",
     "spec/spec_helper.rb",
     "spec/index_spec.rb",
     "spec/models/user.rb",
     "spec/models/post.rb",
     "spec/models/comment.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 0"])
    else
      s.add_dependency(%q<activerecord>, [">= 0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 0"])
  end
end

