# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{foreign_key_migrations}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Micha\305\202 \305\201omnicki"]
  s.date = %q{2010-03-13}
  s.description = %q{Foreign Key Migrations is a plugin that automatically generates foreign-key
constraints when creating tables. It uses SQL-92 syntax and as such should be compatible with most databases that support foreign-key constraints.}
  s.email = %q{michal.lomnicki@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "CHANGELOG",
     "MIT-LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "foreign_key_migrations.gemspec",
     "generators/foreign_key_migration/foreign_key_migration_generator.rb",
     "generators/foreign_key_migration/templates/migration.rb",
     "init.rb",
     "install.rb",
     "lib/foreign_key_migrations.rb",
     "lib/red_hill_consulting/foreign_key_migrations/active_record/base.rb",
     "lib/red_hill_consulting/foreign_key_migrations/active_record/connection_adapters/table_definition.rb",
     "lib/red_hill_consulting/foreign_key_migrations/active_record/migration.rb"
  ]
  s.homepage = %q{http://github.com/mlomnicki/foreign_key_migrations}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Automatically generate foreign-key constraints when creating tables}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<redhillonrails_core>, [">= 1.0.0"])
    else
      s.add_dependency(%q<redhillonrails_core>, [">= 1.0.0"])
    end
  else
    s.add_dependency(%q<redhillonrails_core>, [">= 1.0.0"])
  end
end

